.PHONY: system system_clean
system: check_config output
	$(MAKE) -C "$(OBC_APPFS_SOURCE_DIR)" all OBC_TOP_DIR="$(OBC_TOP_DIR)" CROSS_COMPILE="$(OBC_TOOLCHAIN_PREFIX)" TOOLCHAIN_SYSROOT="$(OBC_TOOLCHAIN_SYSROOT)"
	$(MAKE) -C "$(OBC_THIRD_PART_DIR)" all OBC_TOP_DIR="$(OBC_TOP_DIR)" CROSS_COMPILE="$(OBC_TOOLCHAIN_PREFIX)" TOOLCHAIN_SYSROOT="$(OBC_TOOLCHAIN_SYSROOT)"
system_clean:
	$(MAKE) -C "$(OBC_APPFS_SOURCE_DIR)" clean OBC_TOP_DIR="$(OBC_TOP_DIR)" CROSS_COMPILE="$(OBC_TOOLCHAIN_PREFIX)" || true
	$(MAKE) -C "$(OBC_THIRD_PART_DIR)" clean OBC_TOP_DIR="$(OBC_TOP_DIR)" CROSS_COMPILE="$(OBC_TOOLCHAIN_PREFIX)" || true
