
obj-y += obc_base.o


obj-y += board/board_config.o
obj-$(CONFIG_SOC_K3_AM625) += board/am62x/board_config_am62x.o
obj-$(CONFIG_BOARD_CONFIG_IMX6ULL) += board/imx/board_config_imx6ull.o

obj-y += cmd/cmd_updatex.o
obj-y += cmd/cmd_bootk.o
obj-y += cmd/cmd_obcflash.o

obj-y += common/obc_blk.o
obj-y += common/obc_blk_mmc.o
obj-y += common/obc_blk_flash.o
obj-y += common/obc_pack.o
