#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
# 挂载必要的文件系统
mount -t proc none /proc
mount -t sysfs none /sys


for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
        *.sh)
            # Source shell script for speed.
            (
                trap - INT QUIT TSTP
                set start
                . $i
            )
            ;;
        *)
            # No sh extension, so fork subprocess.
            $i start
            ;;
    esac
done

# 启动一个 shell
exec /bin/sh
